name: steak

networks:
  pre-event-networks:
    driver: bridge

services:
  app:
    build: .
    image: steak:latest
    container_name: steak-server
    ports:
      - "8888:8888"

  postgres:
    image: postgres:latest
    container_name: pre-event-postgres
    restart: always
    environment:
      POSTGRES_USER: bravos
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: steakdb
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: pre-event-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - pre-event-networks
    restart: always

  mongo:
    image: mongo:latest
    container_name: pre-event-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
